---
title: "CB Entropy"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(SportsAnalytics270)
library(dplyr)
library(tidyr)
library(ggplot2)
library(reshape2)
```

```{r}

data("f_data_sm")
data <- f_data_sm %>%
  select(-c("H","D", "A"))

data <- data %>% drop_na()

f_long <- data %>%
  select(SEASON, COUNTRY, DATE,HOMETEAM,AWAYTEAM,FTSC) %>%
  gather(key='flag', value = 'Team',-c(SEASON, COUNTRY, FTSC,DATE)) %>%
  separate(FTSC, into = c('g1','g2'),sep = '-') %>%
  mutate(scored=ifelse(flag=='HOMETEAM',as.numeric(g1),as.numeric(g2)),
         conceded=ifelse(flag=='HOMETEAM',as.numeric(g2),as.numeric(g1)),
        WL=ifelse(scored>conceded,'W',ifelse(scored<conceded,"L",'D')),
        Points=ifelse(scored>conceded,3,ifelse(scored<conceded,0,1))) %>%
    select(-c(g1,g2))


f <- f_long %>%
  group_by(SEASON, COUNTRY, Team, WL) %>%
  summarise(Total_Points = sum(Points), Matches = n(), scored = sum(scored), 
            conceded = sum(conceded)) %>%
  group_by(SEASON, COUNTRY) %>%
  spread(WL,Matches) %>%
  group_by(SEASON, COUNTRY, Team) %>%
  summarise(Scored=sum(scored), Conceded=sum(conceded),W=sum(W,na.rm = TRUE), 
            D=sum(D,na.rm = TRUE),L=sum(L,na.rm = TRUE),Total_Points=sum(Total_Points)) %>%
  mutate(Position = dense_rank(desc(rank(Total_Points,ties.method = "first"))),
         Matches=D+L+W)%>%
  arrange(Position)


```

```{r}
f <- f %>% mutate(Wpct = Total_Points/3/Matches, Wpct = Wpct/sum(Wpct))


head(f)                  
```
```{r}
H <- f %>% group_by(SEASON, COUNTRY) %>% summarize(H = -sum(Wpct * log2(Wpct + 10^(-10))), n = n())
H <- H %>% mutate(Hm = -n * 1/n * log2(1/n))
H <- H %>% mutate(R = H / Hm)
H
```


```{r}
HHI <- f %>% filter(COUNTRY == "Portugal") %>% 
  group_by(SEASON) %>%
  mutate(Perc = Total_Points / sum(Total_Points)) %>%
  summarise(HHI = sum(Perc^2))


df <- left_join(H %>% filter(COUNTRY == "Portugal"), HHI)
df
```
```{r}
ggplot(df, aes(R, HHI)) + geom_point() + geom_smooth(method = lm) 
```


```{r}
df <- left_join(H %>% filter(COUNTRY == "Spain"), ha)

ggplot(df, aes(R, ha)) + geom_point() + geom_smooth(method = lm) 
```

```{r}
df <- df %>% drop_na()
cor(df$R, df$ha)
```




