---
output:
  html_document: default
  pdf_document: default
title: "group 4"
author: "Name"
toc: yes 
toc_depth: '3'
---

```{r setup, include=FALSE, error=FALSE, echo=FALSE}
knitr::opts_chunk$set(include=FALSE, error=FALSE, echo=TRUE)
```

```{r}
libs<-c("caret","tidyr", "ggplot2", "knitr", "dplyr", "purrr", "plotly", "MASS", "BradleyTerry2", "devtools", "reldist")
#load libs, install missing libs
load_libraries<-function(libs){
  new_libs <- libs[!(libs %in% installed.packages()[,"Package"])]
  if(length(new_libs)>0) {install.packages(new_libs)}
  lapply(libs, library, character.only = TRUE)
} 
load_libraries(libs)
install_github("HABET/CSE270")
library("SportsAnalytics270")

```

# Objective

```{r}
data <- f_data_sm %>%
  dplyr::select(-c("H","D", "A"))

data <- data %>% drop_na()

f_long <- data %>%
  dplyr::select(SEASON, COUNTRY, DATE,HOMETEAM,AWAYTEAM,FTSC) %>%
  gather(key='flag', value = 'Team',-c(SEASON, COUNTRY, FTSC,DATE)) %>%
  separate(FTSC, into = c('g1','g2'),sep = '-') %>%
  mutate(scored=ifelse(flag=='HOMETEAM',as.numeric(g1),as.numeric(g2)),
         conceded=ifelse(flag=='HOMETEAM',as.numeric(g2),as.numeric(g1)),
        WL=ifelse(scored>conceded,'W',ifelse(scored<conceded,"L",'D')),
        Points=ifelse(scored>conceded,3,ifelse(scored<conceded,0,1))) %>%
    dplyr::select(-c(g1,g2))


f <- f_long %>%
  group_by(SEASON, COUNTRY, Team, WL) %>%
  summarise(Total_Points = sum(Points), Matches = n(), scored = sum(scored),
            conceded = sum(conceded)) %>%
  group_by(SEASON, COUNTRY) %>%
  spread(WL,Matches) %>%
  group_by(SEASON, COUNTRY, Team) %>%
  summarise(Scored=sum(scored), Conceded=sum(conceded),W=sum(W,na.rm = TRUE),
            D=sum(D,na.rm = TRUE),L=sum(L,na.rm = TRUE),Total_Points=sum(Total_Points)) %>%
  mutate(Position = dense_rank(desc(rank(Total_Points,ties.method = "first"))),
         Matches=D+L+W)%>%
  arrange(Position)
```
```{r}
head(football)
```

# Combined Measure of Home Team Advantage

```{r}
df <- f_data_sm %>% dplyr::select(SEASON, COUNTRY, HOMETEAM, AWAYTEAM, FTHG, FTAG) %>%
  mutate(HW = 1)
df2 <- df %>% mutate(team1 = AWAYTEAM, team2 = HOMETEAM, HW = 0) %>% dplyr::select(SEASON, COUNTRY, team1, team2, FTHG, FTAG, HW)
df <-  df %>% rename(team1 = HOMETEAM , team2 = AWAYTEAM)

df4 <- left_join(df, df2, by=c("SEASON", "COUNTRY","team1", "team2"))
head(df4)

```
```{r}
df4 <- df4 %>% mutate(C = sign((FTHG.x - FTAG.x) - (FTAG.y - FTHG.y))) %>% dplyr::select(SEASON, COUNTRY, team1, team2, C)
df4 <- df4 %>% group_by(SEASON, COUNTRY, C) %>% summarise(count=n()) %>% drop_na() %>% spread(key = "C", value = "count")
colnames(df4) <- c("SEASON", "COUNTRY", "k_1", "k0", "k1")

ha_c <- df4 %>% mutate(k_1 = ifelse(is.na(k_1), 0, k_1),
                      k0 = ifelse(is.na(k0), 0, k0),
                      k1 = ifelse(is.na(k1), 0, k1)) %>% mutate(ha_c = 1 - pbeta(1/2, k1/(k_1+k0+k_1) + 1, k_1/(k_1+k0+k_1) + 1))

```
```{r}
cb_ha <- ha_c %>% dplyr::select(SEASON, COUNTRY, ha_c)
```

# Bradley-Terry based Home Team Advantage

```{r}
f_bt <- f_data_sm %>% mutate(ht_w = ifelse(FTR == "H", 1,
                                  ifelse(FTR == "D", 0.5, 0)),
                             at_w = ifelse(FTR == "A", 1,
                                  ifelse(FTR == "D", 0.5, 0)))
```

```{r}
f_bt1 <- f_bt %>%
  mutate(HOMETEAM = as.factor(HOMETEAM),
         AWAYTEAM = as.factor(AWAYTEAM)) %>%
  group_by(HOMETEAM, AWAYTEAM, SEASON)

f_bt1$HOMETEAM <- data.frame(team = f_bt1$HOMETEAM, at.home = 1)
f_bt1$AWAYTEAM <- data.frame(team = f_bt1$AWAYTEAM, at.home = 0)

```


```{r}
# f_bt1 <- f_bt1 %>% group_by(COUNTRY, SEASON)
# f_bt1 <- f_bt1 %>% do(ha = coefficients(BTm(cbind(ht_w, at_w), HOMETEAM, AWAYTEAM, formula = ~team + at.home, data = ., id="team"))["at.home"])
# 
# f_bt2 <- f_bt1
# 
# f_bt1$ha <- flatten_dbl(f_bt1$ha)
# 
# head(f_bt1)
```
```{r}
# f_bt1 <- f_bt1 %>% rename("ha_bt" = "ha")
```

```{r}
# cb_ha <- left_join(cb_ha, f_bt1, by = c("COUNTRY", "SEASON"))
# head(cb_ha)
```

# Poisson Model based Home Team Advantage
```{r}
league <- f_data_sm %>%
  group_by(COUNTRY, SEASON) %>%
  dplyr::select(SEASON, COUNTRY, HOMETEAM, AWAYTEAM, FTHG, FTAG)

l1 <- data.frame(league[, c("SEASON","COUNTRY", "HOMETEAM", "AWAYTEAM", "FTHG")], Home = 1)
l2 <- data.frame(league[, c("SEASON","COUNTRY", "AWAYTEAM", "HOMETEAM", "FTAG")], Home = 0)

colnames(l1) <- c("SEASON","COUNTRY", "Team", "Opponent", "Goal", "Home")
colnames(l2) <- c("SEASON","COUNTRY", "Team", "Opponent", "Goal", "Home")

l2 <- rbind(l1, l2)
```

```{r}
l2 <- l2 %>% group_by(SEASON, COUNTRY) %>%
  do(ha_pois = exp(coefficients(glm(Goal ~ Team + Opponent + Home, data = ., family=poisson(link=log)))["Home"]))
l2$ha_pois <- flatten_dbl(l2$ha_pois)
```

```{r}
cb_ha <- left_join(cb_ha, l2, by = c("COUNTRY", "SEASON"))
head(cb_ha)
```

```{r}
# ggplot(cb_ha, aes(ha_pois, ha_bt))+geom_point()+facet_wrap(~COUNTRY, nrow=3)
```
```{r echo=TRUE, include=TRUE}
ggplot(cb_ha, aes(ha_pois, ha_c))+geom_point()+facet_wrap(~COUNTRY, nrow=3)
```
```{r}
# ggplot(cb_ha, aes(ha_bt, ha_c))+geom_point()+facet_wrap(~COUNTRY, nrow=3)
```
# Competitive balance

# Entropy

```{r}
f <- f %>% mutate(Wpct = Total_Points/3/Matches, Wpct = Wpct/sum(Wpct))
```

```{r}
H <- f %>% group_by(SEASON, COUNTRY) %>% summarize(H = -sum(Wpct * log2(Wpct + 10^(-10))), n = n())
H <- H %>% mutate(Hm = -n * 1/n * log2(1/n))
H <- H %>% mutate(cb_entropy = H / Hm) %>% dplyr::select(SEASON, COUNTRY, cb_entropy)
H

```
```{r}
cb_ha <- left_join(cb_ha, H, by = c("COUNTRY", "SEASON"))
head(cb_ha)
```

# Surprise Indices

```{r}
data <- f_data_sm %>% 
  left_join(dplyr::select(f, SEASON, COUNTRY, Team, Position), by = c("SEASON" = "SEASON", "COUNTRY" = "COUNTRY", "HOMETEAM" = "Team")) %>%
  rename(HTP = Position)

data <- data %>% 
  left_join(dplyr::select(f, SEASON, COUNTRY, Team, Position), by = c("SEASON" = "SEASON", "COUNTRY" = "COUNTRY", "AWAYTEAM" = "Team")) %>%
  rename(ATP = Position)


data <- data %>% mutate(Surprise_Points = ifelse((FTR == 'A' & HTP < ATP) | (FTR == 'H' & HTP > ATP), 2,
                                         ifelse(FTR == 'D' , 1, 0)))

data <- data %>% mutate(Surprise_Points = Surprise_Points*abs(HTP-ATP))
```

```{r}

sp <- data %>% group_by(SEASON, COUNTRY) %>% summarize(Surprise_Points = sum(Surprise_Points))


sp <- sp %>% left_join(f %>% group_by(SEASON, COUNTRY) %>% summarise(N = n()))
sp <- sp %>% mutate(M = (N - 1) * N * (N + 1) / 3)

sp <- sp %>% mutate(cb_s = Surprise_Points/M) %>% dplyr::select(SEASON, COUNTRY, cb_s)

```
```{r}
head(sp)
```

```{r}
cb_ha <- left_join(cb_ha, sp, by = c("COUNTRY", "SEASON"))
head(cb_ha)
```

# Gini Competitive Balance
```{r}
Gini <- f %>% group_by(SEASON, COUNTRY) %>% summarize(cb_gini = gini(Wpct))
Gini
```

```{r}
cb_ha <- left_join(cb_ha, Gini, by = c("COUNTRY", "SEASON"))
head(cb_ha)
```

```{r}
ggplot(cb_ha, aes(cb_gini, cb_s))+geom_point()+facet_wrap(~COUNTRY, nrow=3)
```

# Calculating HHI and Noll-Scully
```{r}
head(f)
```

```{r}
adj_HHI <- f %>%
  group_by(SEASON, COUNTRY) %>%
  mutate(Perc = Wpct / sum(Wpct)) %>%
  summarise(id_s = 0.5/sqrt(n()),  cb_hhi = sum(Perc^2)-1/n(), cb_ns = sd(Perc)/id_s) %>% dplyr::select(-id_s)

head(adj_HHI)
```

```{r}
cb_ha <- left_join(cb_ha, adj_HHI, by = c("COUNTRY", "SEASON"))
head(cb_ha)
```


```{r echo=TRUE, include=TRUE}
# fig <- plot_ly(cb_ha, x = ~-1*cb_hhi, y = ~ha_pois, alpha = 3, color = ~cb_hhi)
# fig <- fig %>% add_markers(marker = list(line = list(color = "black", width = 0.5)))
# fig <- fig %>% layout(
#   title = "HHI vs HA Drop-Down",
#   xaxis = list(domain = c(0.1, 1)),
#   yaxis = list(title = "y"),
#   updatemenus = list(
#     list(
#       y = 0.8,
#       buttons = list(
# 
#         list(method = "restyle",
#              args = list("type", "scatter"),
#              label = "Scatter"),
# 
#         list(method = "restyle",
#              args = list("type", "histogram2d"),
#              label = "2D Histogram")))
#   ))
# 
# fig
# ```
# 
# ```{r}
# ggplot(bt_cb, aes(x = ha, y = HHI)) + geom_point() + geom_smooth(method = lm) + facet_wrap(~COUNTRY, nrow = 6, ncol = 5)
# cor(without_sct$ha, without_sct$HHI)
# ```
# 
# 
# ```{r}
# ggplot(bt_cb, aes(x = ha, y = HHI)) + geom_point() + geom_smooth(method = lm)
# ```
# 
# 
# ```{r}
# fig1 <- plot_ly(bt_cb, x = ~ha, y = ~HHI, alpha = 3, color = ~HHI)
# fig1 <- fig1 %>% add_markers(marker = list(line = list(color = "black", width = 0.5)))
# fig1 <- fig1 %>% layout(
#   title = "BTM-drop down",
#   xaxis = list(domain = c(0.1, 1)),
#   yaxis = list(title = "y"),
#   updatemenus = list(
#     list(
#       y = 0.8,
#       buttons = list(
# 
#         list(method = "restyle",
#              args = list("type", "scatter"),
#              label = "Scatter"),
# 
#         list(method = "restyle",
#              args = list("type", "histogram2d"),
#              label = "2D Histogram")))
#   ))
# 
# fig1
# 
# ```
# 
# 
# ```{r}
# fig2 <- plot_ly(df, x = ~HHI, y = ~ha, alpha = 3, color = ~HHI)
# fig2 <- fig2 %>% add_markers(marker = list(line = list(color = "black", width = 0.5)))
# fig2 <- fig2 %>% layout(
#   title = "HHI,ha-drop down",
#   xaxis = list(domain = c(0.1, 1)),
#   yaxis = list(title = "y"),
#   updatemenus = list(
#     list(
#       y = 0.8,
#       buttons = list(
# 
#         list(method = "restyle",
#              args = list("type", "scatter"),
#              label = "Scatter"),
# 
#         list(method = "restyle",
#              args = list("type", "histogram2d"),
#              label = "2D Histogram")))
#   ))
# 
# fig2
# ```
# 
# 
# ```{r}
# #yet to be completed
# fig3 <- ha_p %>%
#   plot_ly(
#     x = ~SEASON,
#     y = ~ha,
#     type = 'scatter',
#     mode = 'lines',
#     line = list(simplyfy = F))
# fig3 <- fig3 %>% layout(
#   xaxis = list(
#     title = "SEASON",
#     zeroline = F
#   ),
#   yaxis = list(
#     title = "ha",
#     zeroline = F
#   )
# )
# fig3 <- fig3 %>% animation_opts(
#   frame = 100,
#   transition = 0,
#   redraw = FALSE
# )
# fig3 <- fig3 %>% animation_slider(
#   hide = T
# )
# 
# 
# fig3
# ```
# 
# 
# 
# ```{r}
#  ggplot(df, aes(R, HHI)) + geom_point() + geom_smooth(method = lm)
# 
# ```
# 
# ```{r}
# fig4 <- plot_ly(df, x = ~R, y = ~HHI, alpha = 3, color = ~R)
# fig4 <- fig4 %>% add_markers(marker = list(line = list(color = "black", width = 0.5)))
# fig4 <- fig4 %>% layout(
#   title = "R,HHI-drop down",
#   xaxis = list(domain = c(0.1, 1)),
#   yaxis = list(title = "y"),
#   updatemenus = list(
#     list(
#       y = 0.8,
#       buttons = list(
# 
#         list(method = "restyle",
#              args = list("type", "scatter"),
#              label = "Scatter"),
# 
#         list(method = "restyle",
#              args = list("type", "histogram2d"),
#              label = "2D Histogram")))
#   ))
# 
# fig4
# ```
# 
# ```{r}
# df <- left_join(H %>% filter(COUNTRY == "Spain"), ha)
# 
# ggplot(df, aes(R, ha)) + geom_point() + geom_smooth(method = lm)
# 
# ```
# 
# ```{r}
# fig5 <- plot_ly(df, x = ~R, y = ~ha, alpha = 3, color = ~R)
# fig5 <- fig5 %>% add_markers(marker = list(line = list(color = "black", width = 0.5)))
# fig5 <- fig5 %>% layout(
#   title = "R,HHI-drop down",
#   xaxis = list(domain = c(0.1, 1)),
#   yaxis = list(title = "y"),
#   updatemenus = list(
#     list(
#       y = 0.8,
#       buttons = list(
# 
#         list(method = "restyle",
#              args = list("type", "scatter"),
#              label = "Scatter"),
# 
#         list(method = "restyle",
#              args = list("type", "histogram2d"),
#              label = "2D Histogram")))
#   ))
# 
# fig5
# ```
# 
# 
# ```{r}
# country <- "England"
# fig6<- ggplot(HHI %>% filter(COUNTRY == country), aes(SEASON, 1-HHI)) + geom_point() + geom_line()
# ```
# ```{r}
# fig6 <- ggplotly(fig6)
# ```
# 
# 
# ```{r}
# ggplot(HHI %>% filter(COUNTRY == country), aes(SEASON, S)) + geom_point() + geom_line()
# ```
# 
# 
# ```{r}
# ggplot(HHI %>% filter(COUNTRY != "Scotland"), aes(HHI, S)) + geom_point() + geom_smooth(method = lm) + facet_wrap(~COUNTRY)
```