---
title: "ytext"
author: "Sarin Sulahian"
date: "12/3/2020"
output: html_document
---

# Objective
  Our objective for this group project is to see the relationship between competitive balance and home team advantage. What is the correlation between these two? To answer this question, we decided to apply several used methods both for competitive balance and home team advantage to suffice our question.
  
  Let us start off by briefly introducing the main idea behind competitive balance and home team advantage. Competitive balance implies that each team in any given sport or not, enjoys the same probability of outcome to win in each game. So, it refers to the competitiveness among the players in a given sport, which in our case is football. 
  Home team advantage is the idea that describes the benefits of home teams over visiting teams. It basically implies that if two competitors have the same abilities(or not), those who play in their field have some sort of advantage over the other. The factors of this might be the fans supporting the home team more, the bias of referees, psychological or physiological advantages of playing in a familiar setting, and so on.
  
  We calculated everything using football data on several countries and for each season.
  
  Why do we want to find a correlation between the two? It is easy, because it is interesting! It is interesting because we want to see if the competitiveness of a team contributes or has any relationship with the advantage.
           

#Data
For our data, we used f_data_Sm from SportsAnalytics270.
The data contains seasons 1994-2019, the respective countries are: England, France, Germany, Italy, Netherlands, Spain, Greece, Portugal, Scotland, Turkey. 


#Home team advantage

# Combined Measure of Home Team Advantage

1-Combined Measure of Home Team Advantage (source:https://www.mdpi.com/2227-9091/8/3/87/pdf)
  
  
  Combined measure of home advantage is random variable C that can take values $-1$, $0$, and $1$.
$C = -1$ for team T1 if two matches between teams T1 and T2 in a season ended with a better result – measured by
goal differences in matches – for team T1 away from home (at T2’s ground). $C = 0$ for team T1 if goal differences
in both matches were exactly the same from T1’s point of view, and $C = 1$ for team T1 if this team recorded
better result – measured by goal differences in matches – at its own ground. With results hT1: aT2 at the home ground of team T1 and hT2: aT1 at the home ground of team T2 the value of random variable C for team T1 is determined as
           $C = sgn((hT1 - aT2) - (aT1 - hT2))$.
           
Let $Z_r, r = -1, 0, 1$ are random variables which describe number of cases (e.g., for a team in a
season) where it is possible to identify home advantage ($r = 1$), away advantage ($r = -1$), and no
advantage ($r = 0$), i.e., Zr sums number of cases where $C = r$. Vector ($Z_1, Z_0, Z_1$) follows trinomial
distribution with parameters $p_1$, $p_0$, $p_1$, and $K$ with probability function

$p(k_1, k_0, k_1) = \frac{k!}{k_1! \cdot k_0! \cdot k_1!} \cdot p_1^{k_1} \cdot p_0^{k_0} \cdot p_1^{k_1}$ where K is total number of observations of combined measure in a season, $p_1$, $p_0$, $p_1$ are probabilities
of occurring home advantage (r = 1), away advantage (r = -1), and no advantage ($r = 0$). $k_1$, $k_0$, $k_1$
($k_1 + k_0 + k_1 = K$) are observations of appropriate advantage.
Maximum likelihood estimator of parameters $p_r, r = -1, 0, 1$ is
$p^r = \frac{k_r}{K}, r = -1, 0, 1$.

# Bradley-Terry based Home Team Advantage

2-The Bradley-Terry model is a probability model that assumes the outcome of a paired comparison. Given a pair of individuals $i$ and $j$ drawn from the same population, the odds that $i$ beat $j$ are $\frac{a_i}{a_j}$, where ai and aj are positive valued parameteres which represent the abilities of each team or player. 
  $P(i > k) = \frac{p_i}{p_i + p_j}$
   A slight point worth mentioning that the model does not predict draws.

# Poisson Model based Home Team Advantage
3-The Poisson model is discrete probability distribution that expresses the probability of a given number of events occurring in a fixed interval of time.We use the Poisson regression which is part of the Generalized Linear Regression models family.
Lambda is determined by a set of $k$ regressor variable (the $x$'s),the explanatory variables, $x=(x_1,x_2...x_k)$, can be continuous and categorical, which redirects to the poisson regression. These counts are to be modeled in a contingency table where the convention is called a log-linear model.
log link: $\log{(\lambda}) = \beta_0 + \beta_1 \cdot x$ or $\lambda = e^{\beta_0 + \beta_1 \cdot x}$, where $\lambda$ is never negative.

note: We assume that variables are independent based past research using the $chi^2$ test.


#Competitive Balance 

# Entropy
 https://link.springer.com/content/pdf/10.1023/A:1007799730191.pdf 
 
Horowitz (1997) chose to use the relative-entropy measure of information theory to measure seasonal
competitive balance

  Similarly, the minimum entropy or uncertainty about which team might have won
a game selected at random from the schedule, is achieved when the best team wins all games. Relative entropy, $R = H=HM$, measures the degree of uncertainty about which team might have won a randomly-selected game, relative to the maximum uncertainty possible.
  
# Surprise Index
The Surprise Index was introduced by Groot and Groot (2003)- for reference-https://ideas.repec.org/p/ant/wpaper/2005034.html,
it is the ratio between P, the realized surprise points and M, the maximum number of
surprise points that is possible when the teams are perfectly balanced10. Two surprise points are given
when a team looses from a lower ranked team and one point is awarded when the game ends in a tie.
These points are weighted with the rank difference.

# Gini Competitive Balance

The Gini coefficient is originally developed to measure income inequalities. Schmidt (2001) and Schmidt
& Berri (2001) use it to measure the inequality of winning percentages. ?

# Calculating HHI and Noll-Scully
http://www.investopedia.com/terms/h/hhi.asp#ixzz4t8sTjDns

  Herfindahl-Hirschman index comes from economics, and is a commonly accepted measure of market concentration․ Increasing number of the teams affects lower bound (in some cases upper
bound as well)
$HHI = \sum_{i = 1}^{n} \left(\frac{p_i}{ \sum_{i = 1}^{n} p_i } \right)^2$


  The Noll-Scully compares what a league actually looks like to what it would ideally look like. In a perfect world — i.e. one where actual balance matches the ideal — the metric would return a 1.0, meaning
the league is balanced. If the number is above 1.0 it means the teams are further away in wins than we would expect given the ideal.If the number is below 1.0 — which is very rare case— it means the teams are closer in wins than we would expect.

  Ideally the number will be equal to 1, and higher the number means that there is less competition, and if it is closer to 1, it means that the competitive balance is higher.
  $\sigma_{relative} = \frac{\sigma}{ 0.5 / \sqrt{m} }$
  
  
  
  
#Results

By comparing each method to one another, and as seen in the graphs, the overall correlation between the different methods imply the same results. For some methods it may vary, but overall the relationship is not massively different....


#Conclusion
In conclusion,